service: import-service

provider: 
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  iam:
    role:
      statements:
        # Allow functions to list all buckets
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'
        # Allow functions to read/write objects in a bucket
        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::orlov-vitalii-import/*'
        - Effect: Allow
          Action:
            - 'sqs:SendMessage'
          Resource:
            - 'arn:aws:sqs:eu-west-1:475340852272:catalogItemsQueue'

  environment:
    SQS_URL:
      Ref: SQSQueue
  
resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
    - s3:
        bucket: orlov-vitalii-import
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
        existing: true